exclude: 'CHANGELOG.md'
repos:
  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: 'v1.2.0'
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: 'package-lock.json'
    # Prettier for any YAML, README
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  # Check newlines, yaml is valid
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
  # Eslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.20.0'
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-prettier@8.3.0
          - eslint-plugin-svelte3@4.0.0
